name: guildserver
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  shelf: 
  shelf_router: 
  shelf_web_socket: 
  web_socket_channel:
  dotenv:
  uuid: ^4.5.1
  http: ^1.3.0
  googleapis_auth: ^2.0.0
  googleapis:
  shelf_cors_headers: 
  mysql1: 
  bcrypt: ^1.1.3
  timezone: ^0.10.1
  pool: ^1.5.1
  mysql_client: ^0.0.27
  logging_appenders: ^1.3.1
  logging:
dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
